{
 "title": "Main dashboard",
 "time": { "from": "2024-10-02T16:34:43.864Z", "to": "2024-10-02T16:40:43.864Z" },
 "templating": {
  "list": [
   { "name": "server", "query": "artillery-api" },
   {
    "name": "container",
    "query": "1c25-tp-1_node_1, 1c25-tp-1_node_2, 1c25-tp-1_node_3, 1c25-tp-1_cadvisor_1, 1c25-tp-1_grafana_1, 1c25-tp-1_graphite_1,  1c25-tp-1_nginx_1, 1c25-tp-1_bbox_1"
   }
  ]
 },
 "panels": [
  {
   "title": "Scenarios launched (stacked)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "target": "aliasByMetric(stats.gauges.artillery-api.scenarioCounts.*)"
    }
   ]
  },
  {
   "title": "Requests state (stacked)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "alias(sumSeries(stats.gauges.artillery-api.errors.*), 'Errored')"
    },
    {
     "target": "alias(stats.gauges.artillery-api.codes.200, 'Completed')"
    },
    {
     "target": "alias(stats.gauges.artillery-api.pendingRequests, 'Pending')"
    },
    {
     "target": "alias(stats.gauges.artillery-api.codes.429, 'Limited')"
    },
    {
     "target": "alias(stats.gauges.artillery-api.codes.503, 'API Connection Error')"
    }
   ]
  },
  {
   "title": "Response time (client-side)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "alias(stats.gauges.artillery-api.scenarioDuration.max, 'Upper')"
    },
    {
     "target": "alias(stats.gauges.artillery-api.scenarioDuration.median, 'Median')"
    }
   ]
  },
  {
   "title": "Resources",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "alias(removeBelowValue(asPercent(derivative(keepLastValue(stats.gauges.cadvisor.-.cpu_cumulative_usage, 100)), 10000000000), 0.0001), 'CPU')"
    },
    {
     "target": "alias(asPercent(stats.gauges.cadvisor.-.memory_working_set, 34359738368), 'Memory')"
    }
   ]
  },
  {
   "title": "Total Request Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "alias(stats.timers.api.request.request_time.upper, 'Upper')"
    },
    {
     "target": "alias(stats.timers.api.request.request_time.median, 'Median')"
    }
   ]
  },
  {
   "title": "API Consumption Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "target": "alias(stats.timers.api.request.consume_api_time.upper, 'Upper')"
    },
    {
     "target": "alias(stats.timers.api.request.consume_api_time.median, 'Median')"
    }
   ]
  }
 ]
}